apiVersion: v1
kind: Namespace
metadata:
  name: nginx-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-operator
  namespace: nginx-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-operator
  namespace: nginx-operator
spec:
  selector:
    matchLabels:
      app: nginx-operator
  replicas: 1 
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: nginx-operator
    spec:
      serviceAccountName: nginx-operator
      containers:
      - name: operator
        image: localhost:5000/nginx-operator
        imagePullPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-operator-admin
subjects:
- kind: ServiceAccount
  name: nginx-operator
  namespace: nginx-operator
roleRef:
  kind: ClusterRole
  name: nginx-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-operator
rules:
- apiGroups:
  - ""
  - "extensions"
  - "apps"
  resources:
  - deployments
  - services
  - pods
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - "fr.wilda"
  resources:
  - '*'
  verbs:
  - '*'
